<?php

namespace JemaBundle\Repository;

/**
 * BlockSurferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockSurferRepository extends \Doctrine\ORM\EntityRepository
{
}
