<?php

namespace JemaBundle\Repository;

/**
 * ServiceCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCatRepository extends \Doctrine\ORM\EntityRepository
{
}
