-
    id: 1
    name: Index
    access: public
    pages:
        -
            name: index
            access: public
            route: index
        -
            name: page2
            access: public
            route: page2
-
    id: 2
    name: Contact
    access: public
    pages:
        -
            name: megamenu1
            access: public
            pages:
                -
                    name: Contact us
                    access: public
                    route: page3
                -
                    name: Come see us
                    access: public
                    route: page4
        -
            name: megamenu2
            access: public
            pages:
                -
                    name: Contact us
                    access: public
                    route: page3
                -
                    name: Come see us
                    access: public
                    route: page4